[2024-06-30T06:16:06.407+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-30T06:16:06.461+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: DAG_python_operator_V1.greet_function manual__2024-06-30T06:14:03.582074+00:00 [queued]>
[2024-06-30T06:16:06.475+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: DAG_python_operator_V1.greet_function manual__2024-06-30T06:14:03.582074+00:00 [queued]>
[2024-06-30T06:16:06.476+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 6
[2024-06-30T06:16:06.494+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): greet_function> on 2024-06-30 06:14:03.582074+00:00
[2024-06-30T06:16:06.511+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2602) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-30T06:16:06.504+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'DAG_python_operator_V1', 'greet_function', 'manual__2024-06-30T06:14:03.582074+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/dag_python_operator.py', '--cfg-path', '/tmp/tmpxwbw8wri']
[2024-06-30T06:16:06.512+0000] {standard_task_runner.py:63} INFO - Started process 2603 to run task
[2024-06-30T06:16:06.513+0000] {standard_task_runner.py:91} INFO - Job 25: Subtask greet_function
[2024-06-30T06:16:06.577+0000] {task_command.py:426} INFO - Running <TaskInstance: DAG_python_operator_V1.greet_function manual__2024-06-30T06:14:03.582074+00:00 [running]> on host cf712bcdd57c
[2024-06-30T06:16:06.711+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='bavenraj' AIRFLOW_CTX_DAG_ID='DAG_python_operator_V1' AIRFLOW_CTX_TASK_ID='greet_function' AIRFLOW_CTX_EXECUTION_DATE='2024-06-30T06:14:03.582074+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-30T06:14:03.582074+00:00'
[2024-06-30T06:16:06.713+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-30T06:16:06.732+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-30T06:16:06.734+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_python_operator.py", line 11, in greet
    name = ti.xcoms_pull(task_ids = 'get_name' )
           ^^^^^^^^^^^^^
AttributeError: 'TaskInstance' object has no attribute 'xcoms_pull'. Did you mean: 'xcom_pull'?
[2024-06-30T06:16:06.762+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=DAG_python_operator_V1, task_id=greet_function, run_id=manual__2024-06-30T06:14:03.582074+00:00, execution_date=20240630T061403, start_date=20240630T061606, end_date=20240630T061606
[2024-06-30T06:16:06.782+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 25 for task greet_function ('TaskInstance' object has no attribute 'xcoms_pull'; 2603)
[2024-06-30T06:16:06.808+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-30T06:16:06.834+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-30T06:16:06.838+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
